name: build_app
on:
  push:
    branches:
    - main

env:
  MY_APP_NAME: Reaper
  PRIMARY_COLOR: abebcb
  SECONDARY_COLOR: 54e89e
  TERTIARY_COLOR: 158f52


jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 12.x

    - name: Get Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.3.7

    # - name: Install Android gems
    #   working-directory: ${{ github.workspace }}/android
    #   run: bundle install

    - name: Install dependencies
      working-directory: ${{ github.workspace }}
      run: flutter pub get

    - name: Change our app ID
      working-directory: ${{ github.workspace }}
      run: flutter pub run change_app_package_name:main com.$MY_APP_NAME

    - name: Change our app icon
      working-directory: ${{ github.workspace }}
      run: flutter pub run icons_launcher:create

    - name: Build the app
      working-directory: ${{ github.workspace }}
      run: flutter build appbundle --dart-define=myAppName=$MY_APP_NAME --dart-define=Primary=$PRIMARY_COLOR
        --dart-define=Secondary=$SECONDARY_COLOR --dart-define=Tertiary=$TERTIARY_COLOR

    - name: Upload artifacts to Github
      uses: actions/upload-artifact@v2
      with:
        name: final-apk
        path: build/app/outputs/apk/release/app-release.apk

  # get-artifacts:
  #   name: Download our apk
  #   runs-on: macos-latest
  #   needs: build-apk
  #   steps:
  #   - name: Download artifacts
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: final-apk

  #   - name: Test Artifact download
  #     run: ls -R
